import Head from "next/head";
import MainLayout from "@/components/layouts/main";
import TableComponent from "@/components/table/table";
import { Layout, theme } from "antd";
import { useEffect } from "react";
import { useRouter } from "next/router";
const { Content } = Layout;
const data = [];
for (let i = 0; i < 100; i++) {
  data.push({
    key: i,
    name: `Edward ${i}`,
    age: 32 + Math.floor(Math.random() * 11),
    address: `London Park no. ${i}`,
  });
}

const columns = [
  {
    title: "Company Name",
    width: 100,
    dataIndex: "name",
    key: "name",
    fixed: "left",
  },
  {
    title: "Company Email",
    width: 100,
    dataIndex: "age",
    key: "age",
    sorter: (a, b) => a.age - b.age,
  },
  {
    title: "Company Website",
    dataIndex: "address",
    key: "1",
    width: 100,
  },
  {
    title: "Company Website",
    dataIndex: "address",
    key: "1",
    width: 100,
  },
  {
    title: "# Contacts",
    key: "operation",
    width: 100,
    render: () => <a>action</a>,
  },
  {
    title: "ID",
    dataIndex: "age",
    key: "operation",
    width: 100,
    fixed: "",
  },
];

export default function Home() {
  const router = useRouter();
  const {
    token: { colorBgContainer },
  } = theme.useToken();

  useEffect(() => {
    if (
      !localStorage.getItem("userProfile") &&
      !sessionStorage.getItem("userProfile")
    ) {
      router.push("/login");
    }
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Content
        className="mainlayout__content"
        style={{
          padding: 24,
          height: "100vh",
          background: colorBgContainer,
        }}
      >
        <h2>Companies</h2>
        <TableComponent data={data} columns={columns} />
        <p>UnikCore Automation. © 2023 UnikCore</p>
      </Content>
    </>
  );
}

Home.getLayout = function getLayout(page) {
  return <MainLayout>{page}</MainLayout>;
};
